### ISSUE TITLE
更新版本时.ejs文件出错

### ISSUE THREAD

**Issue by yumeko11** [sabrinaluo/hexo-theme-replica#41]
ERROR ReferenceError: E:\blog\yumeko11Blog\themes\replica\layout\layout.ejs:7
       5| <%- partial('_partial/navbar') %>
       6| <div class="main-container">
 >> 7|   <%- body %>
       8| </div>
       9| <%- partial('_partial/footer') %>
     10| <%- partial('_partial/script') %>

body is not defined
    at eval (E:\blog\yumeko11Blog\themes\replica\layout\layout.ejs:21:17)
    at layout (E:\blog\yumeko11Blog\node_modules\ejs\lib\ejs.js:682:17)
    at _View._compiled (E:\blog\yumeko11Blog\node_modules\hexo\lib\theme\view.js:136:50)
    at _View.render (E:\blog\yumeko11Blog\node_modules\hexo\lib\theme\view.js:39:17)
    at E:\blog\yumeko11Blog\node_modules\hexo\lib\hexo\index.js:64:21
    at tryCatcher (E:\blog\yumeko11Blog\node_modules\bluebird\js\release\util.js:16:23)
    at E:\blog\yumeko11Blog\node_modules\bluebird\js\release\method.js:15:34
    at RouteStream._read (E:\blog\yumeko11Blog\node_modules\hexo\lib\hexo\router.js:47:5)
    at RouteStream.Readable.read (internal/streams/readable.js:462:10)
    at resume_ (internal/streams/readable.js:958:12)
    at processTicksAndRejections (internal/process/task_queues.js:82:21) {
  path: 'E:\\blog\\yumeko11Blog\\themes\\replica\\layout\\layout.ejs'

**Comment by yumeko11** [comment]
很喜欢这个主题 希望帮忙解决一下
